//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.30 at 10:43:09 AM EST 
//


package fileMapper.data.datavo.vdo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fileMapper.data.datavo.vdo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetModifierNameInfo_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_modifier_name_info");
    private final static QName _GetDataType_QNAME = new QName("http://i2b2.idiginfo.fsu.edu/map", "get_dataType");
    private final static QName _PatientType_QNAME = new QName("http://www.i2b2.org/xsd/hive/plugin/", "patient_type");
    private final static QName _GetTermInfo_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_term_info");
    private final static QName _GetCodeInfo_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_code_info");
    private final static QName _GetDirtyState_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_dirty_state");
    private final static QName _GetModifierChildren_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_modifier_children");
    private final static QName _GetModifierCodeInfo_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_modifier_code_info");
    private final static QName _GetNameInfo_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_name_info");
    private final static QName _GetDataTypeField_QNAME = new QName("http://i2b2.idiginfo.fsu.edu/map", "get_dataTypeField");
    private final static QName _GetModifierInfo_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_modifier_info");
    private final static QName _GetOntProcessStatus_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_ont_process_status");
    private final static QName _GetChildren_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_children");
    private final static QName _GetModifiers_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_modifiers");
    private final static QName _UpdateCrcConcept_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "update_crc_concept");
    private final static QName _UpdateConceptTotalnum_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "update_concept_totalnum");
    private final static QName _GetCategories_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_categories");
    private final static QName _GetSchemes_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "get_schemes");
    private final static QName _PluginDragDrop_QNAME = new QName("http://www.i2b2.org/xsd/hive/plugin/", "plugin_drag_drop");
    private final static QName _DeleteChild_QNAME = new QName("http://www.i2b2.org/xsd/cell/ont/1.1/", "delete_child");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fileMapper.data.datavo.vdo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataTypeField }
     * 
     */
    public DataTypeField createDataTypeField() {
        return new DataTypeField();
    }

    /**
     * Create an instance of {@link GetOntProcessStatusType.ProcessStartDate }
     * 
     */
    public GetOntProcessStatusType.ProcessStartDate createGetOntProcessStatusTypeProcessStartDate() {
        return new GetOntProcessStatusType.ProcessStartDate();
    }

    /**
     * Create an instance of {@link VocabRequestType }
     * 
     */
    public VocabRequestType createVocabRequestType() {
        return new VocabRequestType();
    }

    /**
     * Create an instance of {@link MatchIntType }
     * 
     */
    public MatchIntType createMatchIntType() {
        return new MatchIntType();
    }

    /**
     * Create an instance of {@link GetTermInfoType }
     * 
     */
    public GetTermInfoType createGetTermInfoType() {
        return new GetTermInfoType();
    }

    /**
     * Create an instance of {@link GetOntProcessStatusType.ProcessEndDate }
     * 
     */
    public GetOntProcessStatusType.ProcessEndDate createGetOntProcessStatusTypeProcessEndDate() {
        return new GetOntProcessStatusType.ProcessEndDate();
    }

    /**
     * Create an instance of {@link GetOntProcessStatusType }
     * 
     */
    public GetOntProcessStatusType createGetOntProcessStatusType() {
        return new GetOntProcessStatusType();
    }

    /**
     * Create an instance of {@link UpdateCrcConceptType }
     * 
     */
    public UpdateCrcConceptType createUpdateCrcConceptType() {
        return new UpdateCrcConceptType();
    }

    /**
     * Create an instance of {@link GetModifierChildrenType }
     * 
     */
    public GetModifierChildrenType createGetModifierChildrenType() {
        return new GetModifierChildrenType();
    }

    /**
     * Create an instance of {@link DndType }
     * 
     */
    public DndType createDndType() {
        return new DndType();
    }

    /**
     * Create an instance of {@link MatchDateType }
     * 
     */
    public MatchDateType createMatchDateType() {
        return new MatchDateType();
    }

    /**
     * Create an instance of {@link GetChildrenType }
     * 
     */
    public GetChildrenType createGetChildrenType() {
        return new GetChildrenType();
    }

    /**
     * Create an instance of {@link MatchStrType }
     * 
     */
    public MatchStrType createMatchStrType() {
        return new MatchStrType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link GetCategoriesType }
     * 
     */
    public GetCategoriesType createGetCategoriesType() {
        return new GetCategoriesType();
    }

    /**
     * Create an instance of {@link GetModifierInfoType }
     * 
     */
    public GetModifierInfoType createGetModifierInfoType() {
        return new GetModifierInfoType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link DeleteChildType }
     * 
     */
    public DeleteChildType createDeleteChildType() {
        return new DeleteChildType();
    }

    /**
     * Create an instance of {@link GetReturnType }
     * 
     */
    public GetReturnType createGetReturnType() {
        return new GetReturnType();
    }

    /**
     * Create an instance of {@link GetModifiersType }
     * 
     */
    public GetModifiersType createGetModifiersType() {
        return new GetModifiersType();
    }

    /**
     * Create an instance of {@link UpdateConceptTotalNumType }
     * 
     */
    public UpdateConceptTotalNumType createUpdateConceptTotalNumType() {
        return new UpdateConceptTotalNumType();
    }

    /**
     * Create an instance of {@link PatientSet }
     * 
     */
    public PatientSet createPatientSet() {
        return new PatientSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VocabRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_modifier_name_info")
    public JAXBElement<VocabRequestType> createGetModifierNameInfo(VocabRequestType value) {
        return new JAXBElement<VocabRequestType>(_GetModifierNameInfo_QNAME, VocabRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://i2b2.idiginfo.fsu.edu/map", name = "get_dataType")
    public JAXBElement<DataType> createGetDataType(DataType value) {
        return new JAXBElement<DataType>(_GetDataType_QNAME, DataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/hive/plugin/", name = "patient_type")
    public JAXBElement<PatientType> createPatientType(PatientType value) {
        return new JAXBElement<PatientType>(_PatientType_QNAME, PatientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTermInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_term_info")
    public JAXBElement<GetTermInfoType> createGetTermInfo(GetTermInfoType value) {
        return new JAXBElement<GetTermInfoType>(_GetTermInfo_QNAME, GetTermInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VocabRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_code_info")
    public JAXBElement<VocabRequestType> createGetCodeInfo(VocabRequestType value) {
        return new JAXBElement<VocabRequestType>(_GetCodeInfo_QNAME, VocabRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReturnType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_dirty_state")
    public JAXBElement<GetReturnType> createGetDirtyState(GetReturnType value) {
        return new JAXBElement<GetReturnType>(_GetDirtyState_QNAME, GetReturnType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetModifierChildrenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_modifier_children")
    public JAXBElement<GetModifierChildrenType> createGetModifierChildren(GetModifierChildrenType value) {
        return new JAXBElement<GetModifierChildrenType>(_GetModifierChildren_QNAME, GetModifierChildrenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VocabRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_modifier_code_info")
    public JAXBElement<VocabRequestType> createGetModifierCodeInfo(VocabRequestType value) {
        return new JAXBElement<VocabRequestType>(_GetModifierCodeInfo_QNAME, VocabRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VocabRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_name_info")
    public JAXBElement<VocabRequestType> createGetNameInfo(VocabRequestType value) {
        return new JAXBElement<VocabRequestType>(_GetNameInfo_QNAME, VocabRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://i2b2.idiginfo.fsu.edu/map", name = "get_dataTypeField")
    public JAXBElement<DataType> createGetDataTypeField(DataType value) {
        return new JAXBElement<DataType>(_GetDataTypeField_QNAME, DataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetModifierInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_modifier_info")
    public JAXBElement<GetModifierInfoType> createGetModifierInfo(GetModifierInfoType value) {
        return new JAXBElement<GetModifierInfoType>(_GetModifierInfo_QNAME, GetModifierInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOntProcessStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_ont_process_status")
    public JAXBElement<GetOntProcessStatusType> createGetOntProcessStatus(GetOntProcessStatusType value) {
        return new JAXBElement<GetOntProcessStatusType>(_GetOntProcessStatus_QNAME, GetOntProcessStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetChildrenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_children")
    public JAXBElement<GetChildrenType> createGetChildren(GetChildrenType value) {
        return new JAXBElement<GetChildrenType>(_GetChildren_QNAME, GetChildrenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetModifiersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_modifiers")
    public JAXBElement<GetModifiersType> createGetModifiers(GetModifiersType value) {
        return new JAXBElement<GetModifiersType>(_GetModifiers_QNAME, GetModifiersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCrcConceptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "update_crc_concept")
    public JAXBElement<UpdateCrcConceptType> createUpdateCrcConcept(UpdateCrcConceptType value) {
        return new JAXBElement<UpdateCrcConceptType>(_UpdateCrcConcept_QNAME, UpdateCrcConceptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateConceptTotalNumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "update_concept_totalnum")
    public JAXBElement<UpdateConceptTotalNumType> createUpdateConceptTotalnum(UpdateConceptTotalNumType value) {
        return new JAXBElement<UpdateConceptTotalNumType>(_UpdateConceptTotalnum_QNAME, UpdateConceptTotalNumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCategoriesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_categories")
    public JAXBElement<GetCategoriesType> createGetCategories(GetCategoriesType value) {
        return new JAXBElement<GetCategoriesType>(_GetCategories_QNAME, GetCategoriesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReturnType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "get_schemes")
    public JAXBElement<GetReturnType> createGetSchemes(GetReturnType value) {
        return new JAXBElement<GetReturnType>(_GetSchemes_QNAME, GetReturnType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DndType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/hive/plugin/", name = "plugin_drag_drop")
    public JAXBElement<DndType> createPluginDragDrop(DndType value) {
        return new JAXBElement<DndType>(_PluginDragDrop_QNAME, DndType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteChildType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ont/1.1/", name = "delete_child")
    public JAXBElement<DeleteChildType> createDeleteChild(DeleteChildType value) {
        return new JAXBElement<DeleteChildType>(_DeleteChild_QNAME, DeleteChildType.class, null, value);
    }

}
