//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.13 at 01:28:07 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fsu.edu/data/datavo/vdo/")
package fileMapper.data.datavo.vdo;
