CREATE OR REPLACE PROCEDURE ADD_MAP_ELEMENT(
MAP_ID NUMBER ,
	SOURCE_ID VARCHAR2 ,
	COLUMN_INDEX NUMBER ,
	ACTIVE VARCHAR2 ,
	TARGET_TABLE VARCHAR2,
	TARGET_FIELD VARCHAR2,
	NAME_ON_SOURCE VARCHAR2, 
	IS_FACT VARCHAR2 ,
	CONCEPT_CD VARCHAR2, 
	IS_KEY VARCHAR2,
	TRANSFORMATION VARCHAR2 ,
	IS_VIRTUAL_COLUMN VARCHAR2 ,
	VIRTUAL_VALUE VARCHAR2
)AS
	ELEMENT_ID NUMBER;
BEGIN
 select max(ELEMENT_ID) into ELEMENT_ID from FILE_MAP_ELEMENTS;
 if   ELEMENT_ID is null  then 
 ELEMENT_ID:=1;
 end if;
 insert into FILE_MAP_ELEMENTS (MAP_ID  ,
	SOURCE_ID  ,
  ELEMENT_ID,
	COLUMN_INDEX  ,
	ACTIVE  ,
	TARGET_TABLE ,
	TARGET_FIELD ,
	NAME_ON_SOURCE , 
	IS_FACT  ,
	CONCEPT_CD , 
	IS_KEY ,
	TRANSFORMATION  ,
	IS_VIRTUAL_COLUMN  ,
	VIRTUAL_VALUE )
  values(
  MAP_ID  ,
	SOURCE_ID  ,
  ELEMENT_ID,
	COLUMN_INDEX  ,
	ACTIVE  ,
	TARGET_TABLE ,
	TARGET_FIELD ,
	NAME_ON_SOURCE , 
	IS_FACT  ,
	CONCEPT_CD , 
	IS_KEY ,
	TRANSFORMATION  ,
	IS_VIRTUAL_COLUMN  ,
	VIRTUAL_VALUE
  );
  
END ADD_MAP_ELEMENT;